# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    github:
      owner: capnfabs
      name: tap
    # Template for the url which is determined by the given Token (github or gitlab)
    url_template: "https://github.com/capnfabs/grouse/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://github.com/capnfabs/grouse"
    description: "A diff tool for Hugo websites."
    install: |
      bin.install "grouse"
