# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: capnfabs/grouse-integration:0.1
    steps:
      - checkout
      - run: go build ./...
      - run: go test ./...
