// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import git "github.com/capnfabs/grouse/internal/git"
import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// AddWorktree provides a mock function with given fields: dst
func (_m *Repository) AddWorktree(dst string) (git.Worktree, error) {
	ret := _m.Called(dst)

	var r0 git.Worktree
	if rf, ok := ret.Get(0).(func(string) git.Worktree); ok {
		r0 = rf(dst)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(git.Worktree)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dst)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClearSourceControlledFilesFromWorktree provides a mock function with given fields:
func (_m *Repository) ClearSourceControlledFilesFromWorktree() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CommitEverythingInWorktree provides a mock function with given fields: message
func (_m *Repository) CommitEverythingInWorktree(message string) (git.Hash, error) {
	ret := _m.Called(message)

	var r0 git.Hash
	if rf, ok := ret.Get(0).(func(string) git.Hash); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Get(0).(git.Hash)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResolveCommit provides a mock function with given fields: ref
func (_m *Repository) ResolveCommit(ref string) (git.ResolvedUserRef, error) {
	ret := _m.Called(ref)

	var r0 git.ResolvedUserRef
	if rf, ok := ret.Get(0).(func(string) git.ResolvedUserRef); ok {
		r0 = rf(ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(git.ResolvedUserRef)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RootDir provides a mock function with given fields:
func (_m *Repository) RootDir() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
