// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import git "github.com/capnfabs/grouse/internal/git"
import mock "github.com/stretchr/testify/mock"

// ResolvedCommit is an autogenerated mock type for the ResolvedCommit type
type ResolvedCommit struct {
	mock.Mock
}

// Hash provides a mock function with given fields:
func (_m *ResolvedCommit) Hash() git.Hash {
	ret := _m.Called()

	var r0 git.Hash
	if rf, ok := ret.Get(0).(func() git.Hash); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(git.Hash)
	}

	return r0
}

// Repo provides a mock function with given fields:
func (_m *ResolvedCommit) Repo() git.Repository {
	ret := _m.Called()

	var r0 git.Repository
	if rf, ok := ret.Get(0).(func() git.Repository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(git.Repository)
		}
	}

	return r0
}
