// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import git "github.com/capnfabs/grouse/internal/git"
import mock "github.com/stretchr/testify/mock"

// ResolvedUserRef is an autogenerated mock type for the ResolvedUserRef type
type ResolvedUserRef struct {
	mock.Mock
}

// Commit provides a mock function with given fields:
func (_m *ResolvedUserRef) Commit() git.ResolvedCommit {
	ret := _m.Called()

	var r0 git.ResolvedCommit
	if rf, ok := ret.Get(0).(func() git.ResolvedCommit); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(git.ResolvedCommit)
		}
	}

	return r0
}

// UserRef provides a mock function with given fields:
func (_m *ResolvedUserRef) UserRef() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
