// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import git "github.com/capnfabs/grouse/internal/git"
import mock "github.com/stretchr/testify/mock"

// Worktree is an autogenerated mock type for the Worktree type
type Worktree struct {
	mock.Mock
}

// Checkout provides a mock function with given fields: commit
func (_m *Worktree) Checkout(commit git.ResolvedCommit) error {
	ret := _m.Called(commit)

	var r0 error
	if rf, ok := ret.Get(0).(func(git.ResolvedCommit) error); ok {
		r0 = rf(commit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Location provides a mock function with given fields:
func (_m *Worktree) Location() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Remove provides a mock function with given fields:
func (_m *Worktree) Remove() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
